### ISSUE TITLE
xcode8 ios 10.0.1 真机无法测试

### ISSUE THREAD

**Issue by candialala** [macacajs/macaca-ios#35]
> > xctest-client.js:156:14 [master] pid:20740 
> > Testing failed:
> >     Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
> > 
> > xctest-client.js:156:14 [master] pid:20740 *\* TEST FAILED **
> > 
> > xctest-client.js:164:14 [master] pid:20740 xctest client exit with code: 65, signal: null

相同的用例，9.3的真机可以执行。10系统的模拟器也可以执行。
已重装libimobiledevice ： brew reinstall  libimobiledevice
已给webdriveragentrunner重签名：修改webdriveragentrunner Product Bundle Identifier
已添加WebDriverAgentLib和WebDriverAgentRunner两个targets的证书，选择一个team
方法都试过，还是不行。

**Comment by candialala** [comment]
> > ```
> > 1) "before all" hook
> > ```
> > 
> > responseHandler.js:11:12 [master] pid:20740 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> > responseHandler.js:23:14 [master] pid:20740 Send HTTP Respone to Client: 405 Method Not Allowed
> > 
> > ```
> > 2) "after all" hook
> > ```
> > 
> >   0 passing (5m)
> >   2 failing
> > 
> >   1) XXXXX "before all" hook:
> >      Error: timeout of 300000ms exceeded. Ensure the done() callback is being called in this test.

  2) XXXXX "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

**Comment by Wanghuayin** [comment]
问题解决了吗？

**Comment by xudafeng** [comment]
https://testerhome.com/topics/6503
