### ISSUE TITLE
Failed to install app 'com.xx.xx', please install the app manually. this.device.installUntilReady is not a function

### ISSUE THREAD

**Issue by oosnail** [macacajs/macaca-ios#62]
iOS真机使用uirecord 失败，不能安装应用。
iOS真机使用uirecord 失败，不能安装应用。

uirecord 日志：
录制服务器监听在端口: 9765 录制浏览器已开启 手机打开失败，请检查macaca是否配置正确？ Failed to install app 'com.xx.xx', please install the app manually.

macaca server 日志：

index.js:18:12 [master] pid:45146 webdriver server start with config:
{ port: 4444,
verbose: true,
always: true,
ip: '10.12.54.132',
host: 'zhangtianchendeMacBook-Pro.local',
loaded_time: '2017-11-20 14:45:24' }
middlewares.js:17:10 [master] pid:45146 base middlewares attached
router.js:133:10 [master] pid:45146 router set
webdriver sdk launched
responseHandler.js:11:12 [master] pid:45146 Recieve HTTP Request from Client[2017-11-20 14:45:44]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","app":"/Users/ztcq/Desktop/ipa/d.zip","udid":"199ce7e631ef60de8b6702******"}}
session.js:47:10 [master] pid:45146 Creating session, sessionId: aa0310ab-e463-4699-b097-b58a9ecb827b.
ios-deploy
helper.js:162:12 [master] pid:45146 Unzipping local app form /Users/ztcq/Desktop/ipa/d.zip
CFBundleIdentifier is com.xx.xx
Get bundleId com.xx.xx from plist /var/folders/ds/d_bj7pq17q72td0wdkyvg_km0000gn/T/Payload/Info.plist
macaca-ios.js:279:12 [master] pid:45146 App 'com.xx.xx' is not installed.
macaca-ios.js:284:14 [master] pid:45146 this.device.installUntilReady is not a function
responseHandler.js:56:12 [master] pid:45146 Send Error Respone to Client: UnknownError: Failed to install app 'com.xx.xx', please install the app manually.
responseHandler.js:62:14 [master] pid:45146 UnknownError: Failed to install app 'com.xx.xx', please install the app manually.
at IOS.startRealDevice (/usr/local/lib/node_modules/macaca-ios/lib/macaca-ios.js:285:13)
at IOS.startRealDevice.next ()
at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
at
我注意到报错中的一句话：
this.device.installUntilReady is not a function

**Comment by oosnail** [comment]
查看源码
commits: e73c3e3c011ee48c58ddb25722de8f9964f6092b 
replace to installUtilReady
`
将
 yield this.device.install(app);
改为
yield this.device.installUntilReady(app, bundleId);
`
可是installUntilReady方法 跑不起来
于是我自己改回来，ios真机就能跑起来了。
