### ISSUE TITLE
npm i macaca-ios -g突然装不上了

### ISSUE THREAD

**Issue by cary1179** [macacajs/macaca-ios#71]
git clone下来本地尝试安装，发现是`xctest-wd`更新到了1.4.7都安装不上了，npm i xctest-wd@1.4.6就没问题。

```bash
** TEST BUILD FAILED **

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/build/Build/Products'
    at Object.readdirSync (fs.js:783:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/scripts/install.js:116:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xctestwd@1.4.7 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xctestwd@1.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miratto/.npm/_logs/2019-03-15T10_08_40_139Z-debug.log
```

**Comment by SirCYong** [comment]
感谢楼主，使用1.4.6 成功，

**Comment by SamuelZhaoY** [comment]
reinstall xctestwd@1.4.10, the issue has been fixed

**Comment by iwhyshop** [comment]
试试看
