### ISSUE TITLE
iPhone XS 真机启动，模拟器会被调起来

### ISSUE THREAD

**Issue by syl0224** [macacajs/macaca-ios#75]
有在本地尝试这个 https://github.com/macacajs/app-inspector/pull/218/commits/043a28dae422f22feee719f1004e205693042f90 的方法 ，但会报另一个错误

```
>> macaca-ios.js:175:12 [master] pid:46225 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:46225 xcode version: 10.2.1
>> XCTestWD version: 1.4.18
>> xctest-client.js:230:20 [master] pid:46225 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:46225 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:227:20 [master] pid:46225 hitted for default mode
>> xctestwd start with port: 8900
>> proxy.js:55:14 [master] pid:46225 Proxy: /wd/hub/session:POST to http://127.0.0.1:8900/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.xxx.xxx","platformName":"iOS"}}
>> xctest-client.js:230:20 [master] pid:46225 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> xctest-client.js:230:20 [master] pid:46225 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:63:22 [master] pid:46225 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> xctest-client.js:309:14 [master] pid:46225 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8900
>> xctest-client.js:322:14 [master] pid:46225 killing runnerProc pid: 47530
>> responseHandler.js:56:12 [master] pid:46225 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8900
>> responseHandler.js:62:14 [master] pid:46225 Error: connect ECONNREFUSED 127.0.0.1:8900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)

  Error: connect ECONNREFUSED 127.0.0.1:8900
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)

>> xctest-client.js:242:16 [master] pid:46225 xctest client exit with code: null, signal: SIGKILL
```

**Comment by syl0224** [comment]
fixed in https://github.com/macacajs/macaca-ios/pull/76 and https://github.com/macacajs/ios-utils/pull/6
